export const countryCodeList: { [key: string]: string } = {
  Australia: 'AU',
  Bahrain: 'BH',
  Azerbaijan: 'AZ',
  Canada: 'CA',
  China: 'CN',
  France: 'FR',
  Austria: 'AT',
  UK: 'GB',
  Hungary: 'HU',
  Belgium: 'BE',
  Italy: 'IT',
  Netherlands: 'NL',
  Russia: 'RU',
  Spain: 'ES',
  Singapore: 'SG',
  Japan: 'JP',
  USA: 'US',
  Mexico: 'MX',
  Brazil: 'BR',
  Monaco: 'MC',
  Qatar: 'QA',
  Portugal: 'PT',
  'Saudi Arabia': 'SA',
  UAE: 'AE',
  Turkey: 'TR',
  Malaysia: 'MY',
  'United Arab Emirates': 'AE',
  Argentina: 'AR',
  Germany: 'DE',
  India: 'IN',
  'South Korea': 'KR',
  Morocco: 'MA',
  'South Africa': 'ZA',
  Sweden: 'SE',
  Switzerland: 'CH',
  'United States': 'US',
};
